### ISSUE TITLE
No gulp-vueify package

### ISSUE THREAD

**Issue by peremenov** [Zahajki/gulp-vueify#1]
https://www.npmjs.com/package/gulp-vueify shows 404 error

**Comment by druppy** [comment]
I think the reason is that you need to get it directly from github and not from npmjs.org :-)

Just try this, as stated on the frontpage :

``` sh
npm install Zahajki/gulp-vueify --save-dev
```

**Comment by peremenov** [comment]
Thanks (must read carefully)!
P.S. Why not publish to npm?

**Comment by druppy** [comment]
I have no idea, ask the original author :-) 

But, github is ok for me ...

**Comment by Zahajki** [comment]
@peremenov There was no big reason, and I've just published the package to npmjs.com!
@druppy Thank you for your kind comments!
